name: seeing deploy list
# on main branch updates
on:
  workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
              #install serverless
            - name: Install Serverless Framework
              run: npm install -g serverless
            - name: Install Serverless prune plugin
              run: sls plugin install -n serverless-prune-plugin
              # authentication
            - name: Serverless AWS authentication
              run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY_DEPLOY }} --secret ${{ secrets.AWS_SECRET_DEPLOY }}
            - name: Deploy
              run: sls deploy list --region us-east-2 --config serverless.yml
