name: roll back to timestampeee
# on main branch updates
on:
  workflow_dispatch:
    inputs:
      timestamp:
        description: 'add timestamp'
        required: true
      
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
              #install serverless
            - name: Deploy
              run: echo "sls  deploy --region us-east-2 --config serverless-api-${{github.event.inputs.timestamp}}.yml"
            - name: Deploy
              run: cd New_folder
            - name: Deploy
              run: ls
              


